### ISSUE TITLE
Update release team membership rtest_release_team

### ISSUE THREAD

**Issue by MariuszSzczepanikSpyrosoft** [ros2-gbp/ros2-gbp-github-org#822]
# Updates to rtest_release_team membership.

## New team members

[@MariuszSzczepanikSpyrosoft](https://github.com/Beam-and-Spyrosoft/rtest/blob/main/rtest/package.xml#L9)
[@slci](https://github.com/Beam-and-Spyrosoft/rtest/blob/main/rtest/package.xml#L8)

**Comment by nuclearsandwich** [comment]
Resolved by #811.

**Comment by MariuszSzczepanikSpyrosoft** [comment]
Hi @nuclearsandwich, I still received an error when I try to push --dry-run to rtest-release repository:

```
git push origin master --dry-run
ERROR: Permission to ros2-gbp/rtest-release.git denied to MariuszSzczepanikSpyrosoft.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
